module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  daisyui: {
    themes: [
      {
        light: {
          primary: "#176F6B",
          secondary: "#040c2c",
          accent: "#FFEDD5",
          neutral: "#fd7e14",
          "base-100": "#ffffff",
          info: "#98A8DD",
          success: "#e68330",
          warning: "#DF7E07",
          error: "#FA5C5C",
        },
      },
      // {
      //   dark: {
      //     primary: "#dadada",
      //     secondary: "#e4aa48",
      //     orange: "#fd7e14",
      //     yellow: "#ffc107",
      //     accent: "#37cdbe",
      //     neutral: "#3d4451",
      //     "base-100": "#ffffff",
      //     blue: "#007bff",
      //     indigo: "#6610f2",
      //     purple: "#6f42c1",
      //     pink: "#e83e8c",
      //     red: "#dc3545",
      //     green: "#28a745",
      //     teal: "#20c997",
      //     cyan: "#17a2b8",
      //     gray: "#6c757d",
      //     grayDark: "#343a40",
      //     // primary: "#007bff",
      //     // secondary: "#6c757d",
      //     success: "#28a745",
      //     info: "#17a2b8",
      //     warning: "#ffc107",
      //     danger: "#dc3545",
      //     light: "#f8f9fa",
      //     dark: "#343a40",
      //   },
      // },
    ],
  },
  plugins: [require("daisyui")],
}